spring.application.name=loan_engine
spring.datasource.url=jdbc:postgresql://postgres:5432/loan_db
spring.datasource.username=db_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.change-log= classpath:/db/changelog/db.changelog-master.yaml

logging.level.root=INFO
logging.level.proov.inbank.loan_engine=DEBUG


